dataset:
  name: drive
  image_size: [512, 512]
  ignore_index: 255
  hf_name: Zomba/DRIVE-digital-retinal-images-for-vessel-extraction
  hf_train_split: train
  hf_test_split: validation
  val_ratio: 0.2
